version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ~/SWE/node.js/docker01:/usr/share/nginx/html
    depends_on: [run-serv-calc]
  run-serv-calc:
    image: http-serv-calc:latest
    build: .
    ports:
      - "9006:8345"
